POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1Y2FzIiwiaWQiOiI2MDg1N2YwMDg5NjMxYjgwNGQ1MmYxMjEiLCJpYXQiOjE2MTkzNjE2MDMsImV4cCI6MTYxOTM2NTIwM30.muxt9OFpHtantDG-AWN0VNpIg_Sauj92pJIybc9DJaQ

{
    "title": "lol2",
    "author": "lol2",
    "url":"www.lol.lol",
    "likes":1
}